### ISSUE TITLE
Apple Watch: "The Network Connection Was Lost"

### ISSUE THREAD

**Issue by IchSchreiGleich** [IPCams/BugTracker#28]
**Describe the bug**
On Apple Watch, the jpg-Image is not shown. Error message: "The Network Connection Was Lost". Pressing reload button doen't improve the situation. 

**To Reproduce**
Edit a camera in the main app with snapshot path filled in.

**Expected behavior**
Probaly to see an image on my watch? ;)

**App Version**
2.1

**Device & OS Version**
iPhone 8, iOS 14.3

**Additional context**
The snapshot path was tried with both hostname and ip address and with both http and https. Nothing worked.

**Comment by tylerjonesio** [comment]
Thanks for the detailed bug report. This is definitely not the behavior that we want to see!

I have a couple of questions for you that will hopefully help get to the bottom of the issue.
1. Have you tried the snapshot field with just last part/path of the url? For example if the jpeg url is `http://192.168.0.100:80/cgi-bin/snapshot.cgi` just try the `cgi-bin/snapshot.cgi` part.
2. What is the network connection on your watch in comparison to your phone? For example, Is your watch using your phone's network connection via bluetooth, is it on the same wifi network, a different wifi network, using LTE, etc.

**Comment by IchSchreiGleich** [comment]
Hi,
thank you for your reply

1. Now i've tried only the path. With and w/o prepended slash. Same error message.
2. The Watch is connected via iPhone to my local network. The same as the camera is in.

My wifi is a private cass A network (10.0.0.0/8) including a switche, an additional gateway and of course a firewall. Maybe this is an problem? - On the other hand the link to the snapsht path works in Safari (iPhone).

**Comment by cnelson-pdx** [comment]
If it helps, im also seeing this issue. 
Watch is connected to wifi, i have Cameras on a separate VLAN, but my watch and phone are in a group to allow access to camera vlan via unifi firewall rule. RTSP and snapshot url work in safari on phone. 

I have also attempted both full URL or just the /cgi-bin/snapshot.cgi in the snapshot path. I also have attempted to pull a image from the blue iris webserver and have been unable to get that feed to load either.

Apple Watch 6 (watchOS 7.2) and iPhone 12 pro (iOS 14.3)

**Comment by tylerjonesio** [comment]
@cnelson-pdx it sounds like I have a pretty similar network setup to what you have except with a pfsense firewall in-between my vlans instead of unifi. So I know this type of setup should be able to work, but not sure why it is erroring out. 

From what I understand the `The Network Connection Was Lost` error is one that usually crops up when something on the other end drops the connection. That could be the camera, a firewall, or some other network issue in-between. With that said, it is still a pretty generic error and doesn't really help with getting to the bottom of the issue. I'll look at getting an update put together that includes some deeper debug logging in hopes that it can help highlight what is happening. 

Question for you all, what cameras are you all using? And what does the snapshot url look like? One other thing I want to do is make sure there aren't any issues parsing the url in a way that would be causing a bad request.

**Comment by cnelson-pdx** [comment]
All Amcrest cameras in my setup, most are IP8M-T2499EW but I have a single IP5M-T1179EW as well. 

URLs were identified via ispyconnect database. 

"/cgi-bin/snapshot.cgi" is the base for all amcrest snapshot urls, though there are some modifiers shown in the ispy database that i've tried with no luck "/cgi-bin/snapshot.cgi?chn=0&u=admin&p=admin" and "/cgi-bin/snapshot.cgi?1"

Thanks for the Development work. bought a lifetime pro license as soon as i saw the apple watch feature listed in the app update, just to give what i can to keep up the good work.

**Comment by cnelson-pdx** [comment]
Got my IP8M-T2499EW working this afternoon. Changed from RTSP to HTTP. this makes sense because RTSP is on 554 by default, the snapshot url isn't fed on that port (duh! - Wish I would have tried changing protocols earlier, sorry!) so maybe if we can enter a full URL in the snapshot path when using RTSP, or have an optional port field for the snapshot URL when using RTSP that might allow both to work. Am I following this logic right?

**Comment by tylerjonesio** [comment]
Yep, I think you got it! The app was trying to be smart and infer some defaults based on the camera setup and automatically map rtsp:// to http:// and port 554 to 80 for the snapshot url. But it looks like there was an issue with the port mapping where 554 was still being used incorrectly.

I've just released an update (2.1.1) on the App Store that is in the process of rolling out. It fixes the specific port mapping issue but also makes it where you can enter a fully qualified URL in the snapshot field as well. A url like `http://192.168.0.100:80/cgi-bin/snapshot.cgi` or just a path like `/cgi-bin/snapshot.cgi` should work. This should help in the case where the snapshot path uses nonstandard/different ports and/or schemes. I've also added a little extra messaging and error handling around this to show the snapshot url the app is using in order to help surface potential connection problems. 

Hopefully this update fixes the issue for you all! Thanks for your support and the help in figuring this out.

**Comment by IchSchreiGleich** [comment]
Just loaded Version 2.1.1 and filled in full qualified url "http://<host>:<port>/<snapshotpath>". Same error message as before: "The Network Connection Was Lost". Tried with hostname and ip, tried with port (80) and w/o port (only "http")

But what's "special", my snapshotpath is using authentication over http (dont judge me 😛). But although username und password is set, the Watch still show the error above.

**Comment by IchSchreiGleich** [comment]
Just tested again. Works as intended. Issue can be closed.

**Comment by tylerjonesio** [comment]
Glad to hear it is working!
